config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

 get 'say/goodbye'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



end

app/controllers/hello_controller.rb
class HelloController < ApplicationController

	<h1>Hello from Rails!</h1>

end

app/controllers/say_controller.rb
class SayController < ApplicationController
 
  def hello
  	@time = Time.now

  	@files = Dir.glob('*' )
  	@display_name1= goodnight("Jyoti")
  	@display_name2 = goodnight("asf")

  	@sd=sec;



end

 
  def goodbye
  end



def goodnight(name)
result = 'Good night, ' + name.downcase
return result
end


def sec

  	inst_section = {
:cello=> 'string' ,
:clarinet=> 'woodwind' ,
:drum=> 'percussion' ,
:oboe=> 'woodwind' ,
:trumpet=> 'brass' ,
:violin=> 'string'
}


result=inst_section[:oboe]
result1=inst_section[:cello]
result2=inst_section[:bassoon]


newresult=[result, result1, result2]
return newresult;
end




# def create say_goodnight(name)  
#   result = "Good night, #{name}"  
#   return result  
# end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper

end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Training</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>
It was nice having you here.


<p>
Say <a href="/say/hello">Hello</a>!
</p> 

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>
It is now <%= @display_name1 %>
<%= @sd %>


<!-- <p>
Say <a href="/say/goodbye">Goodbye</a>!
</p> -->


<p>

<%= link_to "Time to say Goodbyeerert!" , say_goodbye_path %>
</p>



 
<!-- "ecp"='expression'

#{ expression } -->



</p>